import { useEffect, useState } from "react";
import type { Editor } from "@tiptap/core";
import { useEditorState } from "@tiptap/react";
import { Bold, Braces, Code2, Image, Italic, Link, List, ListChecks, ListOrdered, Minus, MoreHorizontal, Paperclip, Plus, Quote, Redo2, Strikethrough, Underline, Undo2, Video } from "lucide-react";

const fonts = [["system", "System Default", ""], ["inter", "Inter", "Inter"], ["segoe", "Segoe UI", "Segoe UI"], ["arial", "Arial", "Arial"], ["georgia", "Georgia", "Georgia"], ["lora", "Lora", "Lora"], ["jetbrains", "JetBrains Mono", "JetBrains Mono"]] as const;
const sizes = [8, 9, 10, 11, 12, 14, 16, 18, 20, 24, 28, 32, 36, 48, 64, 72];

function Button({ label, active, disabled, onClick, children, closeMenu }: { label: string; active?: boolean; disabled?: boolean; onClick: () => void; children: React.ReactNode; closeMenu?: boolean }) {
  return <button type="button" className={active ? "active" : ""} title={label} aria-label={label} aria-pressed={active} disabled={disabled} onClick={(event) => { onClick(); if (closeMenu) event.currentTarget.closest("details")?.removeAttribute("open"); }}>{children}</button>;
}

export function CompactRichTextToolbar({ editor, language, attachmentDisabled, onImage, onAttachment, onLink, onYoutube }: { editor: Editor | null; language: "vi" | "en"; attachmentDisabled?: boolean; onImage: () => void; onAttachment: () => void; onLink: () => void; onYoutube: () => void }) {
  const vi = language === "vi";
  const state = useEditorState({ editor, selector: ({ editor: current }) => current ? { heading: current.isActive("heading", { level: 1 }) ? "h1" : current.isActive("heading", { level: 2 }) ? "h2" : current.isActive("heading", { level: 3 }) ? "h3" : "paragraph", fontFamily: String(current.getAttributes("textStyle").fontFamily || ""), fontSize: Number.parseInt(String(current.getAttributes("textStyle").fontSize || "16"), 10) || 16, bold: current.isActive("bold"), italic: current.isActive("italic"), underline: current.isActive("underline"), strike: current.isActive("strike"), bullet: current.isActive("bulletList"), ordered: current.isActive("orderedList"), task: current.isActive("taskList"), quote: current.isActive("blockquote"), code: current.isActive("code"), codeBlock: current.isActive("codeBlock"), canUndo: current.can().chain().focus().undo().run(), canRedo: current.can().chain().focus().redo().run() } : null });
  const [fontSize, setFontSize] = useState("16");
  useEffect(() => setFontSize(String(state?.fontSize ?? 16)), [state?.fontSize]);
  if (!editor || !state) return <div className="rich-toolbar toolbar-loading" />;
  const applySize = (value: number) => { const next = Math.min(96, Math.max(8, Number.isFinite(value) ? value : 16)); setFontSize(String(next)); editor.chain().focus().setFontSize(`${next}px`).run(); };
  const fontValue = fonts.find((font) => font[2] === state.fontFamily)?.[0] ?? "system";
  return <div className="rich-toolbar rich-toolbar-compact" role="toolbar" aria-label={vi ? "Thanh công cụ soạn thảo" : "Editor toolbar"}>
    <select aria-label={vi ? "Kiểu đoạn" : "Paragraph style"} value={state.heading} onChange={(event) => { const value = event.target.value; if (value === "paragraph") editor.chain().focus().setParagraph().run(); else editor.chain().focus().toggleHeading({ level: Number(value.slice(1)) as 1 | 2 | 3 }).run(); }}><option value="paragraph">{vi ? "Đoạn văn" : "Paragraph"}</option><option value="h1">Heading 1</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option></select>
    <span className="toolbar-separator" /><Button label="Bold" active={state.bold} onClick={() => editor.chain().focus().toggleBold().run()}><Bold size={16} /></Button><Button label="Italic" active={state.italic} onClick={() => editor.chain().focus().toggleItalic().run()}><Italic size={16} /></Button><Button label="Underline" active={state.underline} onClick={() => editor.chain().focus().toggleUnderline().run()}><Underline size={16} /></Button>
    <span className="toolbar-separator" /><Button label={vi ? "Danh sách" : "Bullet list"} active={state.bullet} onClick={() => editor.chain().focus().toggleBulletList().run()}><List size={16} /></Button><Button label={vi ? "Danh sách số" : "Ordered list"} active={state.ordered} onClick={() => editor.chain().focus().toggleOrderedList().run()}><ListOrdered size={16} /></Button><Button label={vi ? "Chèn liên kết" : "Insert link"} onClick={onLink}><Link size={16} /></Button>
    <span className="toolbar-spacer" /><Button label={vi ? "Hoàn tác" : "Undo"} disabled={!state.canUndo} onClick={() => editor.chain().focus().undo().run()}><Undo2 size={16} /></Button><Button label={vi ? "Làm lại" : "Redo"} disabled={!state.canRedo} onClick={() => editor.chain().focus().redo().run()}><Redo2 size={16} /></Button>
    <details className="toolbar-more overlay-anchor" data-overlay-root><summary title={vi ? "Công cụ khác" : "More tools"}><MoreHorizontal size={17} /></summary><div className="menu-popover toolbar-more-popover">
      <label>{vi ? "Phông chữ" : "Font"}<select value={fontValue} onChange={(event) => { const font = fonts.find((item) => item[0] === event.target.value); if (!font?.[2]) editor.chain().focus().unsetFontFamily().run(); else editor.chain().focus().setFontFamily(font[2]).run(); }}>{fonts.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <div className="toolbar-more-size"><span>{vi ? "Cỡ chữ" : "Font size"}</span><div className="font-size-control"><Button label="-" onClick={() => applySize(state.fontSize - 1)}><Minus size={14} /></Button><input list="compact-editor-font-sizes" value={fontSize} onChange={(event) => setFontSize(event.target.value.replace(/[^0-9]/g, ""))} onBlur={() => applySize(Number(fontSize))} /><datalist id="compact-editor-font-sizes">{sizes.map((size) => <option value={size} key={size} />)}</datalist><Button label="+" onClick={() => applySize(state.fontSize + 1)}><Plus size={14} /></Button></div></div>
      <div className="toolbar-more-grid"><Button closeMenu label={vi ? "Gạch ngang" : "Strikethrough"} active={state.strike} onClick={() => editor.chain().focus().toggleStrike().run()}><Strikethrough size={16} /></Button><Button closeMenu label={vi ? "Danh sách việc" : "Checklist"} active={state.task} onClick={() => editor.chain().focus().toggleTaskList().run()}><ListChecks size={16} /></Button><Button closeMenu label={vi ? "Trích dẫn" : "Blockquote"} active={state.quote} onClick={() => editor.chain().focus().toggleBlockquote().run()}><Quote size={16} /></Button><Button closeMenu label={vi ? "Mã nội tuyến" : "Inline code"} active={state.code} onClick={() => editor.chain().focus().toggleCode().run()}><Code2 size={16} /></Button><Button closeMenu label={vi ? "Khối mã" : "Code block"} active={state.codeBlock} onClick={() => editor.chain().focus().toggleCodeBlock().run()}><Braces size={16} /></Button></div>
      <div className="toolbar-more-actions"><Button closeMenu label={vi ? "Chèn ảnh" : "Insert image"} disabled={attachmentDisabled} onClick={onImage}><Image size={16} />{vi ? "Ảnh" : "Image"}</Button><Button closeMenu label={vi ? "Đính kèm file" : "Attach file"} disabled={attachmentDisabled} onClick={onAttachment}><Paperclip size={16} />{vi ? "Tệp" : "File"}</Button><Button closeMenu label={vi ? "Chèn YouTube" : "Insert YouTube"} onClick={onYoutube}><Video size={16} />YouTube</Button></div>
    </div></details>
  </div>;
}
