import { ChevronDown, ChevronRight, FileText, Folder, FolderOpen, MoreHorizontal, Pencil, Plus, RefreshCw, Search, Settings2, SortAsc, Star, Trash2, X } from "lucide-react";
import { useMemo, useState, type DragEvent } from "react";
import type { Folder as FolderRecord, Note } from "../notes/types";

const NOTE_MIME = "application/x-secondbrain-note";
type FilesView = { type: "all" } | { type: "folder"; folderId: string } | { type: "unfiled" };

export function FilesSidebar({ language, notes, folders, selectedId, activeView, query, onQueryChange, onNewNote, onNewFolder, onSelectFolder, onOpenNote, onMoveNote, onToggleFavorite, onTrashNote, onRenameFolder, onTrashFolder, onRefresh, onSettings }: { language: "vi" | "en"; notes: Note[]; folders: FolderRecord[]; selectedId: string | null; activeView: FilesView; query: string; onQueryChange: (value: string) => void; onNewNote: (folderId?: string | null) => void; onNewFolder: (parentId?: string | null) => void; onSelectFolder: (folderId: string | null) => void; onOpenNote: (note: Note, pinned: boolean) => void; onMoveNote: (note: Note, folderId: string | null) => Promise<void>; onToggleFavorite: (note: Note) => void; onTrashNote: (note: Note) => void; onRenameFolder: (folder: FolderRecord) => void; onTrashFolder: (folder: FolderRecord) => void; onRefresh: () => void; onSettings: () => void }) {
  const vi = language === "vi";
  const [sortNewest, setSortNewest] = useState(true);
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  const [dropTarget, setDropTarget] = useState<string | null>(null);
  const text = (value: string) => value.toLocaleLowerCase(vi ? "vi-VN" : "en-US");
  const queryText = text(query.trim());
  const activeNotes = useMemo(() => notes.filter((note) => !note.deleted_at), [notes]);
  const activeFolders = useMemo(() => folders.filter((folder) => !folder.deleted_at), [folders]);
  const matchesNote = (note: Note) => !queryText || text(`${note.title} ${note.content}`).includes(queryText);
  const matchesFolder = (folder: FolderRecord) => !queryText || text(folder.name).includes(queryText);
  const orderNotes = (items: Note[]) => [...items].sort((left, right) => sortNewest ? right.updated_at.localeCompare(left.updated_at) : (left.title || "").localeCompare(right.title || "", vi ? "vi-VN" : "en-US"));
  const foldersByParent = useMemo(() => {
    const index = new Map<string | null, FolderRecord[]>();
    for (const folder of activeFolders) index.set(folder.parent_id, [...(index.get(folder.parent_id) ?? []), folder]);
    index.forEach((items) => items.sort((a, b) => sortNewest ? b.updated_at.localeCompare(a.updated_at) : a.name.localeCompare(b.name, vi ? "vi-VN" : "en-US")));
    return index;
  }, [activeFolders, sortNewest, vi]);
  const descendantIds = (folderId: string): string[] => [folderId, ...(foldersByParent.get(folderId) ?? []).flatMap((folder) => descendantIds(folder.id))];
  const countFolder = (folderId: string) => activeNotes.filter((note) => descendantIds(folderId).includes(note.folder_id ?? "")).length;
  const hasVisibleFolder = (folder: FolderRecord): boolean => matchesFolder(folder) || activeNotes.some((note) => note.folder_id === folder.id && matchesNote(note)) || (foldersByParent.get(folder.id) ?? []).some(hasVisibleFolder);
  const recent = orderNotes(activeNotes.filter(matchesNote)).slice(0, 8);
  const unfiled = orderNotes(activeNotes.filter((note) => note.folder_id === null && matchesNote(note)));
  const toggle = (id: string) => setCollapsed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const dragStart = (event: DragEvent<HTMLElement>, note: Note) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData(NOTE_MIME, note.id); event.dataTransfer.setData("text/plain", note.title || "note"); };
  const dragOver = (event: DragEvent<HTMLElement>, target: string) => { if (!event.dataTransfer.types.includes(NOTE_MIME)) return; event.preventDefault(); event.dataTransfer.dropEffect = "move"; setDropTarget(target); };
  const drop = async (event: DragEvent<HTMLElement>, folderId: string | null) => { event.preventDefault(); setDropTarget(null); const note = activeNotes.find((item) => item.id === event.dataTransfer.getData(NOTE_MIME)); if (note) await onMoveNote(note, folderId); };
  const NoteRow = ({ note, compact = false }: { note: Note; compact?: boolean }) => <article className={`files-note-row ${compact ? "compact" : ""} ${selectedId === note.id ? "active" : ""}`} draggable onDragStart={(event) => dragStart(event, note)}><button className="files-note-main" onClick={() => onOpenNote(note, false)} onDoubleClick={() => onOpenNote(note, true)}><FileText size={15} /><span><strong>{note.title || (vi ? "Chưa có tiêu đề" : "Untitled")}</strong>{!compact && <small>{note.content.trim().slice(0, 76) || (vi ? "Ghi chú trống" : "Empty note")}</small>}</span></button><div className="files-note-actions"><button className={note.is_favorite ? "is-favorite" : ""} title={vi ? "Yêu thích" : "Favorite"} onClick={() => onToggleFavorite(note)}><Star size={13} fill={note.is_favorite ? "currentColor" : "none"} /></button><button className="danger-text" title={vi ? "Chuyển vào Thùng rác" : "Move to Trash"} onClick={() => onTrashNote(note)}><Trash2 size={13} /></button></div></article>;
  const FolderNode = ({ folder, depth = 0 }: { folder: FolderRecord; depth?: number }): React.ReactNode => {
    const children = (foldersByParent.get(folder.id) ?? []).filter(hasVisibleFolder);
    const directNotes = orderNotes(activeNotes.filter((note) => note.folder_id === folder.id && matchesNote(note)));
    const open = !collapsed.has(folder.id) || Boolean(queryText);
    const hasChildren = children.length > 0 || directNotes.length > 0;
    return <div className="files-folder-node" key={folder.id} style={{ "--files-depth": depth } as React.CSSProperties}><div className={`files-folder-row ${activeView.type === "folder" && activeView.folderId === folder.id ? "active" : ""} ${dropTarget === folder.id ? "drop-target" : ""}`} onDragOver={(event) => dragOver(event, folder.id)} onDragLeave={() => setDropTarget(null)} onDrop={(event) => void drop(event, folder.id)}><button className="files-folder-toggle" onClick={() => toggle(folder.id)} aria-label={open ? (vi ? "Thu gọn" : "Collapse") : (vi ? "Mở rộng" : "Expand")}>{hasChildren && (open ? <ChevronDown size={14} /> : <ChevronRight size={14} />)}</button><button className="files-folder-main" onClick={() => onSelectFolder(folder.id)}><Folder size={15} /><strong>{folder.name}</strong><small>{countFolder(folder.id)}</small></button><button className="files-folder-add" title={vi ? "Tạo ghi chú trong thư mục" : "New note in folder"} onClick={() => onNewNote(folder.id)}><Plus size={13} /></button><details className="files-folder-menu" data-overlay-root><summary aria-label={vi ? "Tác vụ thư mục" : "Folder actions"}><MoreHorizontal size={14} /></summary><div className="menu-popover"><button onClick={() => onNewNote(folder.id)}><Plus size={14} />{vi ? "Ghi chú mới" : "New note"}</button><button onClick={() => onNewFolder(folder.id)}><FolderOpen size={14} />{vi ? "Thư mục con" : "New subfolder"}</button><button onClick={() => onRenameFolder(folder)}><Pencil size={14} />{vi ? "Đổi tên" : "Rename"}</button><button className="danger-text" onClick={() => onTrashFolder(folder)}><Trash2 size={14} />{vi ? "Xóa thư mục" : "Delete folder"}</button></div></details></div>{open && <div className="files-folder-children">{directNotes.map((note) => <NoteRow key={note.id} note={note} compact />)}{!hasChildren && <span className="files-empty-inline">{vi ? "Thư mục trống" : "Folder is empty"}</span>}{children.map((child) => <FolderNode key={child.id} folder={child} depth={depth + 1} />)}</div>}</div>;
  };
  const title = vi ? "Tệp" : "Files";
  return <div className="file-explorer-content files-sidebar">
    <header className="file-explorer-header"><div><span className="eyebrow">SECOND BRAIN</span><h2>{title}</h2></div><button className="icon-button small" onClick={onSettings} title={vi ? "Cài đặt" : "Settings"}><Settings2 size={16} /></button></header>
    <div className="file-explorer-toolbar"><button title={vi ? "Ghi chú mới" : "New note"} onClick={() => onNewNote(null)}><Plus size={16} /></button><button title={vi ? "Thư mục mới" : "New folder"} onClick={() => onNewFolder(null)}><FolderOpen size={16} /></button><button title={sortNewest ? (vi ? "Sắp xếp A–Z" : "Sort A–Z") : (vi ? "Sắp xếp mới nhất" : "Sort newest")} onClick={() => setSortNewest((value) => !value)}><SortAsc size={16} /></button><button title={vi ? "Làm mới" : "Refresh"} onClick={onRefresh}><RefreshCw size={15} /></button></div>
    <div className="file-explorer-search"><Search size={15} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder={vi ? "Tìm ghi chú hoặc thư mục..." : "Search notes or folders..."} />{query && <button onClick={() => onQueryChange("")}><X size={14} /></button>}</div>
    <div className="files-sidebar-scroll">
      <section className="files-section"><header><span>{vi ? "Gần đây" : "Recent"}</span><small>{recent.length}</small></header>{recent.length ? recent.map((note) => <NoteRow key={note.id} note={note} />) : <div className="files-empty-section"><FileText size={19} /><span>{vi ? "Chưa có ghi chú gần đây" : "No recent notes"}</span></div>}</section>
      <section className="files-section folders-section"><header><span>{vi ? "Thư mục của bạn" : "Your folders"}</span><button title={vi ? "Thư mục mới" : "New folder"} onClick={() => onNewFolder(null)}><Plus size={14} /></button></header>{(foldersByParent.get(null) ?? []).filter(hasVisibleFolder).map((folder) => <FolderNode key={folder.id} folder={folder} />)}{!(foldersByParent.get(null) ?? []).filter(hasVisibleFolder).length && <div className="files-empty-section"><Folder size={19} /><span>{queryText ? (vi ? "Không tìm thấy thư mục" : "No folders found") : (vi ? "Chưa có thư mục" : "No folders yet")}</span></div>}</section>
      <section className="files-section unfiled-section"><header><button className="files-section-toggle" onClick={() => toggle("__unfiled__")}><span>{collapsed.has("__unfiled__") ? <ChevronRight size={14} /> : <ChevronDown size={14} />}</span>{vi ? "Không có thư mục" : "Unfiled"}<small>{unfiled.length}</small></button><button title={vi ? "Ghi chú mới" : "New note"} onClick={() => onNewNote(null)}><Plus size={14} /></button></header>{!collapsed.has("__unfiled__") && <div className={`files-unfiled-drop ${dropTarget === "__unfiled__" ? "drop-target" : ""}`} onDragOver={(event) => dragOver(event, "__unfiled__")} onDragLeave={() => setDropTarget(null)} onDrop={(event) => void drop(event, null)}>{unfiled.length ? unfiled.map((note) => <NoteRow key={note.id} note={note} compact />) : <div className="files-empty-section"><FileText size={19} /><span>{vi ? "Chưa có ghi chú ngoài thư mục" : "No unfiled notes"}</span></div>}</div>}</section>
    </div>
  </div>;
}
