import { FileText, MoreHorizontal, Plus, RefreshCw, Search, Settings2, Star, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import type { Note } from "../notes/types";

export function FlatNotesSidebar({ language, mode, notes, selectedId, query, onQueryChange, onNewNote, onOpenNote, onToggleFavorite, onTrashNote, onRefresh, onSettings }: { language: "vi" | "en"; mode: "files" | "favorites"; notes: Note[]; selectedId: string | null; query: string; onQueryChange: (value: string) => void; onNewNote: () => void; onOpenNote: (note: Note, pinned: boolean) => void; onToggleFavorite: (note: Note) => void; onTrashNote: (note: Note) => void; onRefresh: () => void; onSettings: () => void }) {
  const vi = language === "vi";
  const [sortNewest, setSortNewest] = useState(true);
  const normalized = query.trim().toLocaleLowerCase(vi ? "vi-VN" : "en-US");
  const visible = useMemo(() => notes.filter((note) => !note.deleted_at && (mode === "files" || Boolean(note.is_favorite)) && (!normalized || `${note.title} ${note.content}`.toLocaleLowerCase(vi ? "vi-VN" : "en-US").includes(normalized))).sort((a, b) => sortNewest ? b.updated_at.localeCompare(a.updated_at) : (a.title || "").localeCompare(b.title || "", vi ? "vi-VN" : "en-US")), [notes, mode, normalized, sortNewest, vi]);
  const title = mode === "favorites" ? (vi ? "Yêu thích" : "Favorites") : (vi ? "Tệp" : "Files");
  return <div className="file-explorer-content flat-notes-sidebar">
    <header className="file-explorer-header"><div><span className="eyebrow">SECOND BRAIN</span><h2>{title}</h2></div><button className="icon-button small" onClick={onSettings} title={vi ? "Cài đặt" : "Settings"}><Settings2 size={16} /></button></header>
    <div className="file-explorer-toolbar">{mode === "files" && <button title={vi ? "Ghi chú mới" : "New note"} onClick={onNewNote}><Plus size={16} /></button>}<button title={sortNewest ? (vi ? "Đang xếp mới nhất" : "Newest first") : (vi ? "Đang xếp A-Z" : "A-Z")} onClick={() => setSortNewest((value) => !value)}><MoreHorizontal size={16} /></button><button title={vi ? "Làm mới" : "Refresh"} onClick={onRefresh}><RefreshCw size={15} /></button></div>
    <div className="file-explorer-search"><Search size={15} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder={vi ? "Tìm ghi chú..." : "Search notes..."} />{query && <button onClick={() => onQueryChange("")}><X size={14} /></button>}</div>
    <div className="flat-note-list">{visible.map((note) => <article key={note.id} className={`flat-note-row ${selectedId === note.id ? "active" : ""}`}><button className="flat-note-main" onClick={() => onOpenNote(note, false)} onDoubleClick={() => onOpenNote(note, true)}><FileText size={16} /><span><strong>{note.title || (vi ? "Chưa có tiêu đề" : "Untitled")}</strong><small>{note.content.trim().slice(0, 80) || (vi ? "Ghi chú trống" : "Empty note")}</small></span></button><div className="flat-note-actions"><button className={note.is_favorite ? "is-favorite" : ""} title={vi ? "Yêu thích" : "Favorite"} onClick={() => onToggleFavorite(note)}><Star size={14} fill={note.is_favorite ? "currentColor" : "none"} /></button><button className="danger-text" title={vi ? "Chuyển vào Thùng rác" : "Move to Trash"} onClick={() => onTrashNote(note)}><Trash2 size={14} /></button></div></article>)}</div>
    {!visible.length && <div className="file-list-empty"><FileText size={28} /><strong>{normalized ? (vi ? "Không tìm thấy ghi chú" : "No notes found") : mode === "favorites" ? (vi ? "Chưa có ghi chú yêu thích" : "No favorite notes yet") : (vi ? "Chưa có ghi chú" : "No notes yet")}</strong><p>{normalized ? (vi ? "Thử một từ khóa khác." : "Try another search term.") : mode === "files" ? (vi ? "Tạo ghi chú đầu tiên để bắt đầu viết." : "Create your first note to start writing.") : (vi ? "Nhấn biểu tượng sao trên một ghi chú để thêm vào đây." : "Star a note to add it here.")}</p>{mode === "files" && !normalized && <button className="secondary-button" onClick={onNewNote}><Plus size={15} />{vi ? "Tạo ghi chú" : "Create note"}</button>}</div>}
  </div>;
}
